# 🐳 Docker Compose pour tester PostgreSQL localement
# Usage: docker-compose -f docker-compose.test.yml up -d

version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: supchaissac-postgres-test
    environment:
      POSTGRES_DB: supchaissac_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password_123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-postgresql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supchaissac_user -d supchaissac_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:

# 🚀 Commandes utiles:
# Démarrer: docker-compose -f docker-compose.test.yml up -d
# Arrêter: docker-compose -f docker-compose.test.yml down
# Logs: docker-compose -f docker-compose.test.yml logs postgres-test
# Nettoyer: docker-compose -f docker-compose.test.yml down -v
