services:
  - type: web
    name: supchaissac
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: supchaissac-db
          property: connectionString

databases:
  - name: supchaissac-db
    plan: free
    databaseName: supchaissac
